### PR TITLE
bump Appsflyer Carthage requirement to 4.8.0

### PR DESCRIPTION
**Pull request by angelodipaolo**
When I clone mparticle-apple-integration-appsflyer, run carthage update, and try to build the kit's Xcode project I get the following error:
```
MPKitAppsFlyer.m:280:32: Use of undeclared identifier 'AFEventParamOrderId'
```

It looks like the [kit code was updated to work with Appsflyer SDK 4.8.0](https://github.com/walmartlabs-wmusiphone/mparticle-apple-integration-appsflyer/commit/245d3e1882e92f8dfab91c76592dbd65f071dcd7) but the kit's Cartfile is still configured to install 4.7.3.

This change updates the Cartfile to use the version of Appsflyer that the kit code requires.

### CODE REVIEW

**Comment by angelodipaolo** [comment]
I suggest testing Carthage installation as part of your CI process to prevent this easy mistake in the future.

**Comment by samdozor** [comment]
@angelodipaolo 100% we will get Carthage into place with CI. AppsFlyer is a unique flower in that they tend to make public API changes regardless of semantic versioning.

**Comment by angelodipaolo** [comment]
@samdozor thanks!
